
export const registerationConstant = {
 USER_RESISTERATATION_REQUEST:'USER_RESISTERATATION_REQUEST',
 USER_RESISTERATATION_SUCCESS:'USER_RESISTERATATION_SUCCESS',
 USER_RESISTERATATION_FAILURE:'USER_RESISTERATATION_FAILURE',
 
}
export const LoginConstant = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
    
   }